//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_vision.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [DisplayName("Upload Photo")]
        public string Photo { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string AlternateText { get; set; }
    }
}
